/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    'cam-nang': CamNang;
    'dich-vu': DichVu;
    'tu-khoa': TuKhoa;
    'dat-lich': DatLich;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'cam-nang': CamNangSelect<false> | CamNangSelect<true>;
    'dich-vu': DichVuSelect<false> | DichVuSelect<true>;
    'tu-khoa': TuKhoaSelect<false> | TuKhoaSelect<true>;
    'dat-lich': DatLichSelect<false> | DatLichSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'cai-dat': CaiDat;
    'ke-hoach-seo': KeHoachSeo;
  };
  globalsSelect: {
    'cai-dat': CaiDatSelect<false> | CaiDatSelect<true>;
    'ke-hoach-seo': KeHoachSeoSelect<false> | KeHoachSeoSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cam-nang".
 */
export interface CamNang {
  id: number;
  /**
   * 25–70 ký tự, có từ khoá chính. Hiện trên Google và tab trình duyệt.
   */
  title: string;
  /**
   * 100–170 ký tự. Đoạn mô tả hiện dưới tiêu đề trên Google.
   */
  description: string;
  keyword: string;
  nhom: 'Khẩn cấp' | 'Ắc quy' | 'Lốp' | 'Tận nơi' | 'Bảo dưỡng' | 'Chẩn đoán' | 'Xe điện' | 'Bản đồ' | 'Thông tin';
  noiDung: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  faq?:
    | {
        q: string;
        a: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Không hiện trên web. Người duyệt dùng để đối chiếu số liệu.
   */
  nguonThamKhao?:
    | {
        ten: string;
        url?: string | null;
        loai?: ('vcwiki' | 'web' | 'hang') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Tự tạo từ tiêu đề nếu để trống. Đổi sau khi đã đăng sẽ làm mất thứ hạng Google.
   */
  slug: string;
  /**
   * Slug tư liệu transcript trong tu-lieu/transcript (không hiện trên web). Bài chép nguyên văn từ 12 chữ liên tiếp sẽ không đăng được.
   */
  tuLieu?: string[] | null;
  ngay: string;
  capNhat?: string | null;
  dichVuLienQuan?: (number | DichVu)[] | null;
  trangThaiDuyet?: ('nhap' | 'choDuyet' | 'canSua' | 'daDuyet') | null;
  ghiChuDuyet?: string | null;
  /**
   * Chỉ người duyệt tick được. Bài có nêu giá phải tick mới đăng được.
   */
  giaDaDuyet?: boolean | null;
  /**
   * Tự cập nhật mỗi lần lưu.
   */
  ketQuaKiemTra?: string | null;
  ghiChuAI?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dich-vu".
 */
export interface DichVu {
  id: number;
  /**
   * Ngắn, ví dụ: Thay ắc quy
   */
  ten: string;
  tomTat: string;
  /**
   * 25–70 ký tự, có từ khoá chính. Hiện trên Google và tab trình duyệt.
   */
  title: string;
  /**
   * 100–170 ký tự. Đoạn mô tả hiện dưới tiêu đề trên Google.
   */
  description: string;
  keyword: string;
  noiDung: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  faq?:
    | {
        q: string;
        a: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Tự tạo từ tiêu đề nếu để trống. Đổi sau khi đã đăng sẽ làm mất thứ hạng Google.
   */
  slug: string;
  /**
   * Slug tư liệu transcript trong tu-lieu/transcript (không hiện trên web). Bài chép nguyên văn từ 12 chữ liên tiếp sẽ không đăng được.
   */
  tuLieu?: string[] | null;
  thuTu?: number | null;
  trangThaiDuyet?: ('nhap' | 'choDuyet' | 'canSua' | 'daDuyet') | null;
  ghiChuDuyet?: string | null;
  /**
   * Chỉ người duyệt tick được. Bài có nêu giá phải tick mới đăng được.
   */
  giaDaDuyet?: boolean | null;
  /**
   * Tự cập nhật mỗi lần lưu.
   */
  ketQuaKiemTra?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Mỗi từ khoá chỉ một bài. Mở một từ khoá chưa có bài rồi bấm "AI viết bản nháp".
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tu-khoa".
 */
export interface TuKhoa {
  id: number;
  tuKhoa: string;
  nhom: 'Khẩn cấp' | 'Ắc quy' | 'Lốp' | 'Tận nơi' | 'Bảo dưỡng' | 'Chẩn đoán' | 'Xe điện' | 'Bản đồ' | 'Thông tin';
  yDinh?: string | null;
  luotTimThang?: string | null;
  dichVu?: (number | null) | DichVu;
  trangThai?: ('chuaViet' | 'dangViet' | 'daCoBai' | 'boQua') | null;
  baiViet?: (number | null) | CamNang;
  ghiChu?: string | null;
  ai?: {
    trangThai?: ('chuaChay' | 'dangChay' | 'xong' | 'loi') | null;
    thongBao?: string | null;
    batDauLuc?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dat-lich".
 */
export interface DatLich {
  id: number;
  trangThai?: ('moi' | 'daGoi' | 'daHen' | 'xong' | 'huy') | null;
  ghiChuNoiBo?: string | null;
  dichVu: string;
  xe: string;
  bienSo?: string | null;
  viTri: string;
  gio?: string | null;
  sdt: string;
  ghiChu?: string | null;
  nguon?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  ten?: string | null;
  vaiTro: 'quanTri' | 'duyetBai' | 'bienTap';
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  hasAPIKey?: boolean | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'cam-nang';
        value: number | CamNang;
      } | null)
    | ({
        relationTo: 'dich-vu';
        value: number | DichVu;
      } | null)
    | ({
        relationTo: 'tu-khoa';
        value: number | TuKhoa;
      } | null)
    | ({
        relationTo: 'dat-lich';
        value: number | DatLich;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cam-nang_select".
 */
export interface CamNangSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  keyword?: T;
  nhom?: T;
  noiDung?: T;
  faq?:
    | T
    | {
        q?: T;
        a?: T;
        id?: T;
      };
  nguonThamKhao?:
    | T
    | {
        ten?: T;
        url?: T;
        loai?: T;
        id?: T;
      };
  slug?: T;
  tuLieu?: T;
  ngay?: T;
  capNhat?: T;
  dichVuLienQuan?: T;
  trangThaiDuyet?: T;
  ghiChuDuyet?: T;
  giaDaDuyet?: T;
  ketQuaKiemTra?: T;
  ghiChuAI?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dich-vu_select".
 */
export interface DichVuSelect<T extends boolean = true> {
  ten?: T;
  tomTat?: T;
  title?: T;
  description?: T;
  keyword?: T;
  noiDung?: T;
  faq?:
    | T
    | {
        q?: T;
        a?: T;
        id?: T;
      };
  slug?: T;
  tuLieu?: T;
  thuTu?: T;
  trangThaiDuyet?: T;
  ghiChuDuyet?: T;
  giaDaDuyet?: T;
  ketQuaKiemTra?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tu-khoa_select".
 */
export interface TuKhoaSelect<T extends boolean = true> {
  tuKhoa?: T;
  nhom?: T;
  yDinh?: T;
  luotTimThang?: T;
  dichVu?: T;
  trangThai?: T;
  baiViet?: T;
  ghiChu?: T;
  ai?:
    | T
    | {
        trangThai?: T;
        thongBao?: T;
        batDauLuc?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dat-lich_select".
 */
export interface DatLichSelect<T extends boolean = true> {
  trangThai?: T;
  ghiChuNoiBo?: T;
  dichVu?: T;
  xe?: T;
  bienSo?: T;
  viTri?: T;
  gio?: T;
  sdt?: T;
  ghiChu?: T;
  nguon?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  ten?: T;
  vaiTro?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  hasAPIKey?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cai-dat".
 */
export interface CaiDat {
  id: number;
  /**
   * Để trống thì nút gọi hiện "Hotline sắp có".
   */
  hotline?: string | null;
  zalo?: string | null;
  email?: string | null;
  /**
   * Để trống thì web ghi chung là thành phố.
   */
  khuVuc?:
    | {
        ten: string;
        id?: string | null;
      }[]
    | null;
  xuongDoiTac?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ke-hoach-seo".
 */
export interface KeHoachSeo {
  id: number;
  nguon?: string | null;
  lichDang?:
    | {
        thang: string;
        baiCamNang?: number | null;
        trangKhac?: string | null;
        chuDe?: string | null;
        id?: string | null;
      }[]
    | null;
  quyTac?:
    | {
        noiDung: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cai-dat_select".
 */
export interface CaiDatSelect<T extends boolean = true> {
  hotline?: T;
  zalo?: T;
  email?: T;
  khuVuc?:
    | T
    | {
        ten?: T;
        id?: T;
      };
  xuongDoiTac?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ke-hoach-seo_select".
 */
export interface KeHoachSeoSelect<T extends boolean = true> {
  nguon?: T;
  lichDang?:
    | T
    | {
        thang?: T;
        baiCamNang?: T;
        trangKhac?: T;
        chuDe?: T;
        id?: T;
      };
  quyTac?:
    | T
    | {
        noiDung?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}