/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    'don-hang': DonHang;
    'tep-don-hang': TepDonHang;
    'danh-gia': DanhGia;
    'danh-muc-dich-vu': DanhMucDichVu;
    'hang-muc-gia': HangMucGia;
    'nhat-ky-gia': NhatKyGia;
    'hang-xe': HangXe;
    'dong-xe': DongXe;
    quan: Quan;
    phuong: Phuong;
    'cam-nang': CamNang;
    'dich-vu': DichVu;
    'tu-khoa': TuKhoa;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'don-hang': DonHangSelect<false> | DonHangSelect<true>;
    'tep-don-hang': TepDonHangSelect<false> | TepDonHangSelect<true>;
    'danh-gia': DanhGiaSelect<false> | DanhGiaSelect<true>;
    'danh-muc-dich-vu': DanhMucDichVuSelect<false> | DanhMucDichVuSelect<true>;
    'hang-muc-gia': HangMucGiaSelect<false> | HangMucGiaSelect<true>;
    'nhat-ky-gia': NhatKyGiaSelect<false> | NhatKyGiaSelect<true>;
    'hang-xe': HangXeSelect<false> | HangXeSelect<true>;
    'dong-xe': DongXeSelect<false> | DongXeSelect<true>;
    quan: QuanSelect<false> | QuanSelect<true>;
    phuong: PhuongSelect<false> | PhuongSelect<true>;
    'cam-nang': CamNangSelect<false> | CamNangSelect<true>;
    'dich-vu': DichVuSelect<false> | DichVuSelect<true>;
    'tu-khoa': TuKhoaSelect<false> | TuKhoaSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'bang-gia-chung': BangGiaChung;
    'lich-nhan-don': LichNhanDon;
    'cai-dat': CaiDat;
    'ke-hoach-seo': KeHoachSeo;
  };
  globalsSelect: {
    'bang-gia-chung': BangGiaChungSelect<false> | BangGiaChungSelect<true>;
    'lich-nhan-don': LichNhanDonSelect<false> | LichNhanDonSelect<true>;
    'cai-dat': CaiDatSelect<false> | CaiDatSelect<true>;
    'ke-hoach-seo': KeHoachSeoSelect<false> | KeHoachSeoSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Đơn khẩn cấp luôn ở đầu danh sách. Đổi trạng thái theo thứ tự; huỷ được khi đơn chưa xong.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "don-hang".
 */
export interface DonHang {
  id: number;
  ma?: string | null;
  loai: 'datLich' | 'khanCap';
  uuTien?: number | null;
  trangThai: 'daNhan' | 'daXepTho' | 'thoDangDen' | 'choDuyetBaoGia' | 'dangSua' | 'choThanhToan' | 'hoanThanh' | 'huy';
  lichSuTrangThai?:
    | {
        trangThai?:
          | ('daNhan' | 'daXepTho' | 'thoDangDen' | 'choDuyetBaoGia' | 'dangSua' | 'choThanhToan' | 'hoanThanh' | 'huy')
          | null;
        luc?: string | null;
        boi?: string | null;
        ghiChu?: string | null;
        id?: string | null;
      }[]
    | null;
  ghiChuNoiBo?: string | null;
  dichVu?: (number | DanhMucDichVu)[] | null;
  suCo?: string | null;
  trieuChung?: string | null;
  tep?: (number | TepDonHang)[] | null;
  khungGio?: {
    ngay?: string | null;
    ma?: string | null;
    nhan?: string | null;
    batDauLuc?: string | null;
  };
  /**
   * Giá khách thấy khi đặt, lưu lại để đối chiếu.
   */
  giaSoBo?: {
    trangThai?: ('coGia' | 'coVanGoiLai' | 'chuaChon') | null;
    tu?: number | null;
    den?: number | null;
    phanKhuc?: string | null;
    dong?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  xe?: {
    hang?: (number | null) | HangXe;
    dong?: (number | null) | DongXe;
    tenXe?: string | null;
    doi?: number | null;
    /**
     * Gõ liền cũng được, tự thêm dấu.
     */
    bienSo?: string | null;
    soKm?: number | null;
    phanKhuc?: ('A' | 'B' | 'C' | 'D') | null;
  };
  viTri?: {
    diaChi?: string | null;
    lat?: number | null;
    lng?: number | null;
    quan?: (number | null) | Quan;
    phuong?: string | null;
    trongVung?: boolean | null;
    etaTu?: number | null;
    etaDen?: number | null;
    choDo?: ('nha' | 'ham' | 'bai' | 'duong') | null;
    ghiChuChoTho?: string | null;
  };
  khach: {
    hoTen?: string | null;
    sdt: string;
  };
  hoaDon?: {
    can?: boolean | null;
    mst?: string | null;
    tenCongTy?: string | null;
    diaChi?: string | null;
    email?: string | null;
  };
  maGioiThieu?: string | null;
  /**
   * Kiểm tra và tính giảm giá: P1.
   */
  maKhuyenMai?: string | null;
  dongY: {
    dongYXuLyDuLieu: boolean;
    dongYLuc?: string | null;
    nhacBaoDuongZalo?: boolean | null;
  };
  nguon?: {
    kenh?: string | null;
    utmSource?: string | null;
    utmMedium?: string | null;
    utmCampaign?: string | null;
    maQR?: string | null;
    trangVao?: string | null;
    referrer?: string | null;
  };
  tichHop?: {
    dieuPhoiId?: string | null;
    guiDieuPhoiLuc?: string | null;
    loiDieuPhoi?: string | null;
    xacNhanKenh?: string | null;
    xacNhanLuc?: string | null;
    loiThongBao?: string | null;
  };
  /**
   * Link theo dõi: /don/<mã này>/. Hết hạn 24 giờ sau khi đơn xong.
   */
  tokenTheoDoi?: string | null;
  ketThucLuc?: string | null;
  hetHanLinkLuc?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Một chỗ cho cả web. Tắt "Nhận đặt lịch" thì dịch vụ ẩn khỏi form đặt lịch.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "danh-muc-dich-vu".
 */
export interface DanhMucDichVu {
  id: number;
  /**
   * Vd BD, AQ
   */
  ma: string;
  ten: string;
  /**
   * Trùng đường dẫn của Trang dịch vụ (vd ac-quy → /dich-vu/ac-quy/).
   */
  slug: string;
  /**
   * Một dòng dưới tên, vd "Kích nổ, thay mới tại chỗ".
   */
  moTaNgan?: string | null;
  ghiChuBangGia?: string | null;
  nutKeuGoi?: string | null;
  thoiGianLam?: string | null;
  thuTu?: number | null;
  /**
   * Tắt = tạm ẩn khỏi form đặt lịch.
   */
  nhanDatLich?: boolean | null;
  /**
   * Tắt với việc phức tạp: khách thấy "Cố vấn gọi lại" thay cho khoảng giá.
   */
  baoGiaSoBo?: boolean | null;
  hienTrenBangGia?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tep-don-hang".
 */
export interface TepDonHang {
  id: number;
  donHang?: (number | null) | DonHang;
  loai?: ('anh' | 'video') | null;
  thoiLuongGiay?: number | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hang-xe".
 */
export interface HangXe {
  id: number;
  ten: string;
  slug: string;
  thuTu?: number | null;
  maVCparts?: string | null;
  nguon?: ('tay' | 'vcparts') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dong-xe".
 */
export interface DongXe {
  id: number;
  hang: number | HangXe;
  ten: string;
  tenDayDu?: string | null;
  /**
   * Tự tạo, vd toyota-vios.
   */
  slug?: string | null;
  /**
   * Để trống = chưa gán (dòng mới từ VCparts).
   */
  phanKhuc?: ('A' | 'B' | 'C' | 'D') | null;
  goiYPhanKhuc?: ('A' | 'B' | 'C' | 'D') | null;
  canGan?: boolean | null;
  doiTu?: number | null;
  doiDen?: number | null;
  xeDien?: boolean | null;
  maVCparts?: string | null;
  nguon?: ('tay' | 'vcparts') | null;
  dongBoLuc?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Quận đang phục vụ và thời gian thợ tới dự kiến. Tắt cả quận hoặc từng phường ở mục Phường.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quan".
 */
export interface Quan {
  id: number;
  ten: string;
  slug: string;
  thanhPho?: string | null;
  etaTu: number;
  etaDen: number;
  ghiChu?: string | null;
  /**
   * Không bắt buộc. Có ranh giới thì kiểm tra được vị trí theo toạ độ kể cả khi bản đồ không trả tên quận.
   */
  ranhGioi?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  dangPhucVu?: boolean | null;
  thuTu?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Chỉ dùng đánh giá thật của khách (có quận, ngày). Đánh giá mẫu không bao giờ hiện trên web chạy thật.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "danh-gia".
 */
export interface DanhGia {
  id: number;
  noiDung: string;
  tenHienThi: string;
  soSao: number;
  ngay: string;
  quan: number | Quan;
  phuong?: string | null;
  dichVu?: (number | null) | DanhMucDichVu;
  nguon?: ('google' | 'zalo' | 'web' | 'khac') | null;
  donHang?: (number | null) | DonHang;
  hienThi?: boolean | null;
  duLieuMau?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hang-muc-gia".
 */
export interface HangMucGia {
  id: number;
  dichVu: number | DanhMucDichVu;
  ten: string;
  loai: 'cong' | 'phuTung';
  /**
   * 0 = Miễn phí
   */
  gia?: number | null;
  donVi?: string | null;
  giaPhanKhuc?: {
    A?: {
      tu?: number | null;
      den?: number | null;
    };
    B?: {
      tu?: number | null;
      den?: number | null;
    };
    C?: {
      tu?: number | null;
      den?: number | null;
    };
    D?: {
      tu?: number | null;
      den?: number | null;
    };
  };
  ghiChu?: string | null;
  baoGiaSoBo?: ('khong' | 'luonCo' | 'coThe') | null;
  nguonGia?: ('tay' | 'vcparts') | null;
  thuTu?: number | null;
  noiBat?: boolean | null;
  tenNgan?: string | null;
  /**
   * Điền khi sửa giá. Sau khi lưu, ô này tự xoá.
   */
  lyDoDoi?: string | null;
  capNhatGiaLuc?: string | null;
  capNhatGiaBoi?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nhat-ky-gia".
 */
export interface NhatKyGia {
  id: number;
  moTa: string;
  hangMuc?: (number | null) | HangMucGia;
  dichVu?: (number | null) | DanhMucDichVu;
  giaCu?: string | null;
  giaMoi?: string | null;
  lyDo?: string | null;
  nguoi?: (number | null) | User;
  tenNguoi?: string | null;
  vaiTro?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  ten?: string | null;
  vaiTro: 'quanTri' | 'quanLyDichVu' | 'bienTap' | 'marketing' | 'dieuPhoi';
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  hasAPIKey?: boolean | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Tắt phường khó vào (vd khu ngoài đê): khách ở đó được mời gọi tư vấn hoặc đặt kéo xe.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "phuong".
 */
export interface Phuong {
  id: number;
  quan: number | Quan;
  ten: string;
  dangPhucVu?: boolean | null;
  ghiChu?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cam-nang".
 */
export interface CamNang {
  id: number;
  /**
   * 25–70 ký tự, có từ khoá chính. Hiện trên Google và tab trình duyệt.
   */
  title: string;
  /**
   * 100–170 ký tự. Đoạn mô tả hiện dưới tiêu đề trên Google.
   */
  description: string;
  keyword: string;
  nhom: 'Khẩn cấp' | 'Ắc quy' | 'Lốp' | 'Tận nơi' | 'Bảo dưỡng' | 'Chẩn đoán' | 'Xe điện' | 'Bản đồ' | 'Thông tin';
  noiDung: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  faq?:
    | {
        q: string;
        a: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Không hiện trên web. Người duyệt dùng để đối chiếu số liệu.
   */
  nguonThamKhao?:
    | {
        ten: string;
        url?: string | null;
        loai?: ('vcwiki' | 'web' | 'hang') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Tự tạo từ tiêu đề nếu để trống. Đổi sau khi đã đăng sẽ làm mất thứ hạng Google.
   */
  slug: string;
  /**
   * Slug tư liệu transcript trong tu-lieu/transcript (không hiện trên web). Bài chép nguyên văn từ 12 chữ liên tiếp sẽ không đăng được.
   */
  tuLieu?: string[] | null;
  ngay: string;
  capNhat?: string | null;
  dichVuLienQuan?: (number | DichVu)[] | null;
  trangThaiDuyet?: ('nhap' | 'choDuyet' | 'canSua' | 'daDuyet') | null;
  ghiChuDuyet?: string | null;
  /**
   * Chỉ người duyệt tick được. Bài có nêu giá phải tick mới đăng được.
   */
  giaDaDuyet?: boolean | null;
  /**
   * Tự cập nhật mỗi lần lưu.
   */
  ketQuaKiemTra?: string | null;
  ghiChuAI?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dich-vu".
 */
export interface DichVu {
  id: number;
  /**
   * Ngắn, ví dụ: Thay ắc quy
   */
  ten: string;
  tomTat: string;
  /**
   * 25–70 ký tự, có từ khoá chính. Hiện trên Google và tab trình duyệt.
   */
  title: string;
  /**
   * 100–170 ký tự. Đoạn mô tả hiện dưới tiêu đề trên Google.
   */
  description: string;
  keyword: string;
  noiDung: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  faq?:
    | {
        q: string;
        a: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Tự tạo từ tiêu đề nếu để trống. Đổi sau khi đã đăng sẽ làm mất thứ hạng Google.
   */
  slug: string;
  /**
   * Slug tư liệu transcript trong tu-lieu/transcript (không hiện trên web). Bài chép nguyên văn từ 12 chữ liên tiếp sẽ không đăng được.
   */
  tuLieu?: string[] | null;
  thuTu?: number | null;
  trangThaiDuyet?: ('nhap' | 'choDuyet' | 'canSua' | 'daDuyet') | null;
  ghiChuDuyet?: string | null;
  /**
   * Chỉ người duyệt tick được. Bài có nêu giá phải tick mới đăng được.
   */
  giaDaDuyet?: boolean | null;
  /**
   * Tự cập nhật mỗi lần lưu.
   */
  ketQuaKiemTra?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Mỗi từ khoá chỉ một bài. Mở một từ khoá chưa có bài rồi bấm "AI viết bản nháp".
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tu-khoa".
 */
export interface TuKhoa {
  id: number;
  tuKhoa: string;
  nhom: 'Khẩn cấp' | 'Ắc quy' | 'Lốp' | 'Tận nơi' | 'Bảo dưỡng' | 'Chẩn đoán' | 'Xe điện' | 'Bản đồ' | 'Thông tin';
  yDinh?: string | null;
  luotTimThang?: string | null;
  dichVu?: (number | null) | DichVu;
  trangThai?: ('chuaViet' | 'dangViet' | 'daCoBai' | 'boQua') | null;
  baiViet?: (number | null) | CamNang;
  ghiChu?: string | null;
  ai?: {
    trangThai?: ('chuaChay' | 'dangChay' | 'xong' | 'loi') | null;
    thongBao?: string | null;
    batDauLuc?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'don-hang';
        value: number | DonHang;
      } | null)
    | ({
        relationTo: 'tep-don-hang';
        value: number | TepDonHang;
      } | null)
    | ({
        relationTo: 'danh-gia';
        value: number | DanhGia;
      } | null)
    | ({
        relationTo: 'danh-muc-dich-vu';
        value: number | DanhMucDichVu;
      } | null)
    | ({
        relationTo: 'hang-muc-gia';
        value: number | HangMucGia;
      } | null)
    | ({
        relationTo: 'nhat-ky-gia';
        value: number | NhatKyGia;
      } | null)
    | ({
        relationTo: 'hang-xe';
        value: number | HangXe;
      } | null)
    | ({
        relationTo: 'dong-xe';
        value: number | DongXe;
      } | null)
    | ({
        relationTo: 'quan';
        value: number | Quan;
      } | null)
    | ({
        relationTo: 'phuong';
        value: number | Phuong;
      } | null)
    | ({
        relationTo: 'cam-nang';
        value: number | CamNang;
      } | null)
    | ({
        relationTo: 'dich-vu';
        value: number | DichVu;
      } | null)
    | ({
        relationTo: 'tu-khoa';
        value: number | TuKhoa;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "don-hang_select".
 */
export interface DonHangSelect<T extends boolean = true> {
  ma?: T;
  loai?: T;
  uuTien?: T;
  trangThai?: T;
  lichSuTrangThai?:
    | T
    | {
        trangThai?: T;
        luc?: T;
        boi?: T;
        ghiChu?: T;
        id?: T;
      };
  ghiChuNoiBo?: T;
  dichVu?: T;
  suCo?: T;
  trieuChung?: T;
  tep?: T;
  khungGio?:
    | T
    | {
        ngay?: T;
        ma?: T;
        nhan?: T;
        batDauLuc?: T;
      };
  giaSoBo?:
    | T
    | {
        trangThai?: T;
        tu?: T;
        den?: T;
        phanKhuc?: T;
        dong?: T;
      };
  xe?:
    | T
    | {
        hang?: T;
        dong?: T;
        tenXe?: T;
        doi?: T;
        bienSo?: T;
        soKm?: T;
        phanKhuc?: T;
      };
  viTri?:
    | T
    | {
        diaChi?: T;
        lat?: T;
        lng?: T;
        quan?: T;
        phuong?: T;
        trongVung?: T;
        etaTu?: T;
        etaDen?: T;
        choDo?: T;
        ghiChuChoTho?: T;
      };
  khach?:
    | T
    | {
        hoTen?: T;
        sdt?: T;
      };
  hoaDon?:
    | T
    | {
        can?: T;
        mst?: T;
        tenCongTy?: T;
        diaChi?: T;
        email?: T;
      };
  maGioiThieu?: T;
  maKhuyenMai?: T;
  dongY?:
    | T
    | {
        dongYXuLyDuLieu?: T;
        dongYLuc?: T;
        nhacBaoDuongZalo?: T;
      };
  nguon?:
    | T
    | {
        kenh?: T;
        utmSource?: T;
        utmMedium?: T;
        utmCampaign?: T;
        maQR?: T;
        trangVao?: T;
        referrer?: T;
      };
  tichHop?:
    | T
    | {
        dieuPhoiId?: T;
        guiDieuPhoiLuc?: T;
        loiDieuPhoi?: T;
        xacNhanKenh?: T;
        xacNhanLuc?: T;
        loiThongBao?: T;
      };
  tokenTheoDoi?: T;
  ketThucLuc?: T;
  hetHanLinkLuc?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tep-don-hang_select".
 */
export interface TepDonHangSelect<T extends boolean = true> {
  donHang?: T;
  loai?: T;
  thoiLuongGiay?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "danh-gia_select".
 */
export interface DanhGiaSelect<T extends boolean = true> {
  noiDung?: T;
  tenHienThi?: T;
  soSao?: T;
  ngay?: T;
  quan?: T;
  phuong?: T;
  dichVu?: T;
  nguon?: T;
  donHang?: T;
  hienThi?: T;
  duLieuMau?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "danh-muc-dich-vu_select".
 */
export interface DanhMucDichVuSelect<T extends boolean = true> {
  ma?: T;
  ten?: T;
  slug?: T;
  moTaNgan?: T;
  ghiChuBangGia?: T;
  nutKeuGoi?: T;
  thoiGianLam?: T;
  thuTu?: T;
  nhanDatLich?: T;
  baoGiaSoBo?: T;
  hienTrenBangGia?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hang-muc-gia_select".
 */
export interface HangMucGiaSelect<T extends boolean = true> {
  dichVu?: T;
  ten?: T;
  loai?: T;
  gia?: T;
  donVi?: T;
  giaPhanKhuc?:
    | T
    | {
        A?:
          | T
          | {
              tu?: T;
              den?: T;
            };
        B?:
          | T
          | {
              tu?: T;
              den?: T;
            };
        C?:
          | T
          | {
              tu?: T;
              den?: T;
            };
        D?:
          | T
          | {
              tu?: T;
              den?: T;
            };
      };
  ghiChu?: T;
  baoGiaSoBo?: T;
  nguonGia?: T;
  thuTu?: T;
  noiBat?: T;
  tenNgan?: T;
  lyDoDoi?: T;
  capNhatGiaLuc?: T;
  capNhatGiaBoi?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nhat-ky-gia_select".
 */
export interface NhatKyGiaSelect<T extends boolean = true> {
  moTa?: T;
  hangMuc?: T;
  dichVu?: T;
  giaCu?: T;
  giaMoi?: T;
  lyDo?: T;
  nguoi?: T;
  tenNguoi?: T;
  vaiTro?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hang-xe_select".
 */
export interface HangXeSelect<T extends boolean = true> {
  ten?: T;
  slug?: T;
  thuTu?: T;
  maVCparts?: T;
  nguon?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dong-xe_select".
 */
export interface DongXeSelect<T extends boolean = true> {
  hang?: T;
  ten?: T;
  tenDayDu?: T;
  slug?: T;
  phanKhuc?: T;
  goiYPhanKhuc?: T;
  canGan?: T;
  doiTu?: T;
  doiDen?: T;
  xeDien?: T;
  maVCparts?: T;
  nguon?: T;
  dongBoLuc?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quan_select".
 */
export interface QuanSelect<T extends boolean = true> {
  ten?: T;
  slug?: T;
  thanhPho?: T;
  etaTu?: T;
  etaDen?: T;
  ghiChu?: T;
  ranhGioi?: T;
  dangPhucVu?: T;
  thuTu?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "phuong_select".
 */
export interface PhuongSelect<T extends boolean = true> {
  quan?: T;
  ten?: T;
  dangPhucVu?: T;
  ghiChu?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cam-nang_select".
 */
export interface CamNangSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  keyword?: T;
  nhom?: T;
  noiDung?: T;
  faq?:
    | T
    | {
        q?: T;
        a?: T;
        id?: T;
      };
  nguonThamKhao?:
    | T
    | {
        ten?: T;
        url?: T;
        loai?: T;
        id?: T;
      };
  slug?: T;
  tuLieu?: T;
  ngay?: T;
  capNhat?: T;
  dichVuLienQuan?: T;
  trangThaiDuyet?: T;
  ghiChuDuyet?: T;
  giaDaDuyet?: T;
  ketQuaKiemTra?: T;
  ghiChuAI?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dich-vu_select".
 */
export interface DichVuSelect<T extends boolean = true> {
  ten?: T;
  tomTat?: T;
  title?: T;
  description?: T;
  keyword?: T;
  noiDung?: T;
  faq?:
    | T
    | {
        q?: T;
        a?: T;
        id?: T;
      };
  slug?: T;
  tuLieu?: T;
  thuTu?: T;
  trangThaiDuyet?: T;
  ghiChuDuyet?: T;
  giaDaDuyet?: T;
  ketQuaKiemTra?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tu-khoa_select".
 */
export interface TuKhoaSelect<T extends boolean = true> {
  tuKhoa?: T;
  nhom?: T;
  yDinh?: T;
  luotTimThang?: T;
  dichVu?: T;
  trangThai?: T;
  baiViet?: T;
  ghiChu?: T;
  ai?:
    | T
    | {
        trangThai?: T;
        thongBao?: T;
        batDauLuc?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  ten?: T;
  vaiTro?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  hasAPIKey?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bang-gia-chung".
 */
export interface BangGiaChung {
  id: number;
  /**
   * Mỗi lần thợ tới, trong vùng phục vụ.
   */
  phiDiLai: number;
  /**
   * Thu khi khách từ chối báo giá chính thức.
   */
  phiKiemTra: number;
  baoHanhPhuTungThang: number;
  baoHanhCongThang: number;
  camKetCuuHoPhut: number;
  coVanGoiLaiPhut: number;
  /**
   * Đúng 4 dòng A, B, C, D. Hiện ở bảng giá để khách biết xe mình thuộc phân khúc nào.
   */
  phanKhuc?:
    | {
        ma: 'A' | 'B' | 'C' | 'D';
        tenNgan: string;
        moTa: string;
        id?: string | null;
      }[]
    | null;
  lyDoDoi?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lich-nhan-don".
 */
export interface LichNhanDon {
  id: number;
  /**
   * Ngoài giờ này, trang gọi gấp mời khách gọi hotline.
   */
  gioNhanGap: {
    tu: string;
    den: string;
  };
  soNgayDatTruoc?: number | null;
  phutChuanBi?: number | null;
  khungGio?:
    | {
        ma: string;
        batDau: string;
        ketThuc: string;
        soDonToiDa: number;
        ngayTrongTuan: ('T2' | 'T3' | 'T4' | 'T5' | 'T6' | 'T7' | 'CN')[];
        id?: string | null;
      }[]
    | null;
  ngayNghi?:
    | {
        ngay: string;
        ten?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cai-dat".
 */
export interface CaiDat {
  id: number;
  /**
   * Để trống thì nút gọi hiện "Hotline sắp có".
   */
  hotline?: string | null;
  email?: string | null;
  zalo?: string | null;
  zaloOaId?: string | null;
  xuongDoiTac?: string | null;
  chinhSachDuLieu?: string | null;
  phapNhan?: string | null;
  mst?: string | null;
  daThongBaoBoCongThuong?: boolean | null;
  diaChi?: string | null;
  googleDanhGiaUrl?: string | null;
  diemGoogle?: number | null;
  soDanhGiaGoogle?: number | null;
  suCoKhanCap?:
    | {
        ma: string;
        ten: string;
        moTa?: string | null;
        dichVu?: (number | null) | DanhMucDichVu;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ke-hoach-seo".
 */
export interface KeHoachSeo {
  id: number;
  nguon?: string | null;
  lichDang?:
    | {
        thang: string;
        baiCamNang?: number | null;
        trangKhac?: string | null;
        chuDe?: string | null;
        id?: string | null;
      }[]
    | null;
  quyTac?:
    | {
        noiDung: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bang-gia-chung_select".
 */
export interface BangGiaChungSelect<T extends boolean = true> {
  phiDiLai?: T;
  phiKiemTra?: T;
  baoHanhPhuTungThang?: T;
  baoHanhCongThang?: T;
  camKetCuuHoPhut?: T;
  coVanGoiLaiPhut?: T;
  phanKhuc?:
    | T
    | {
        ma?: T;
        tenNgan?: T;
        moTa?: T;
        id?: T;
      };
  lyDoDoi?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lich-nhan-don_select".
 */
export interface LichNhanDonSelect<T extends boolean = true> {
  gioNhanGap?:
    | T
    | {
        tu?: T;
        den?: T;
      };
  soNgayDatTruoc?: T;
  phutChuanBi?: T;
  khungGio?:
    | T
    | {
        ma?: T;
        batDau?: T;
        ketThuc?: T;
        soDonToiDa?: T;
        ngayTrongTuan?: T;
        id?: T;
      };
  ngayNghi?:
    | T
    | {
        ngay?: T;
        ten?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cai-dat_select".
 */
export interface CaiDatSelect<T extends boolean = true> {
  hotline?: T;
  email?: T;
  zalo?: T;
  zaloOaId?: T;
  xuongDoiTac?: T;
  chinhSachDuLieu?: T;
  phapNhan?: T;
  mst?: T;
  daThongBaoBoCongThuong?: T;
  diaChi?: T;
  googleDanhGiaUrl?: T;
  diemGoogle?: T;
  soDanhGiaGoogle?: T;
  suCoKhanCap?:
    | T
    | {
        ma?: T;
        ten?: T;
        moTa?: T;
        dichVu?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ke-hoach-seo_select".
 */
export interface KeHoachSeoSelect<T extends boolean = true> {
  nguon?: T;
  lichDang?:
    | T
    | {
        thang?: T;
        baiCamNang?: T;
        trangKhac?: T;
        chuDe?: T;
        id?: T;
      };
  quyTac?:
    | T
    | {
        noiDung?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}